### ISSUE TITLE
Failed to build on linux 6.16.x

### ISSUE THREAD

**Issue by donmor** [WCHSoftGroup/ch35_38x_linux#25]
```
wch_serial.c: In function ‘wch_ser_timeout’:
wch_serial.c:2591:31: error: implicit declaration of function ‘from_timer’; did you mean ‘mod_timer’? [-Wimplicit-function-declaration]
 2591 |     struct wch_ser_port *sp = from_timer(sp, t, timer);
      |                               ^~~~~~~~~~
      |                               mod_timer
wch_serial.c:2591:49: error: ‘timer’ undeclared (first use in this function); did you mean ‘ktimerd’?
 2591 |     struct wch_ser_port *sp = from_timer(sp, t, timer);
      |                                                 ^~~~~
      |                                                 ktimerd
wch_serial.c:2591:49: note: each undeclared identifier is reported only once for each function it appears in
```
`from_timer` has been renamed to `timer_container_of` in 6.16.0. I may make a quick fix.
